name: atics
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - tqdm
  - regex
  - nltk
  - spacy
  - torchvision
  - torchaudio
  - pytorch
  - pytorch-cuda=11.8
  - sentencepiece
  - typing_extensions
  - matplotlib
  - tensorboard
  - pyyaml
  - rich
  - filelock
  - pip:
      - datasets==3.5.0
      - dill
      - fsspec
      - multiprocess
      - senteval==0.1.0
      - protobuf==6.30.2
      - huggingface-hub==0.30.2
      - xxhash